### ISSUE TITLE
how to work with adbkit?

### ISSUE THREAD

**Issue by Restry** [openstf/adbkit-monkey#4]
if i already have the connect with adbkit . 

can i use the device id to connect with adbkit-monkey ?

or adbkit-monkey can only connect with tcp port ?

**Comment by sorccu** [comment]
Use connectTcp or something and then set up monkey.

**Comment by Restry** [comment]
thanks for your reply @sorccu  . please help me another question . here is my code .
it's always wrong . 

can i write like this?

`
import adb from 'adbkit';
import monkey from 'adbkit-monkey';
const client = adb.createClient();

const openRes = await client.openMonkey(id); // here will throw an exception :   Failure: 'cannot bind listener: unknown socket specification '1080''
const forwardRes = await client.forward(id, 1080, 1080);

var monkeyClient = monkey.connect({ port: 1080 });

monkeyClient.multi()
        .touchDown(100, 0)
        .sleep(5)
        .execute(function(err) {
          assert.ifError(err);
          console.log('Dragged out the notification bar');
          client.end();
        });
`

**Comment by sorccu** [comment]
If you use openMonkey you should not create any forwards or connect anything yourself. You should get a functioning monkey client back from openMonkey.

**Comment by Restry** [comment]
thanks .  i have done it

**Comment by shri-0509** [comment]
@Restry  Hi did u ever try running commands like adb shell monkey -p package -v 5000 ?
